<#import "template.ftl" as layout>
<@layout.registrationLayout displayMessage=false; section>
    <#if section = "header">
        Software License
    <#elseif section = "form">
    <div id="kc-terms-text" style="overflow-y: scroll; height:400px; line-height:1; font-size:10px;">
        <p><strong>BY CLICKING ON &ldquo;ACCEPT,&rdquo; DOWNLOADING, OR OTHERWISE USING EPAD, YOU AGREE TO THE FOLLOWING TERMS AND CONDITIONS:</strong></p>
        <p><strong>STANFORD ACADEMIC SOFTWARE SOURCE CODE LICENSE FOR</strong></p>
        <p>&ldquo;ePAD Annotation Platform for Radiology Images&rdquo;</p>
        <p>version 7/27/2020</p>
        <p>This Agreement covers contributions to and downloads from the ePAD project ("ePAD") maintained by The Board of Trustees of the Leland Stanford Junior University ("Stanford").</p>
        <ol>
        <li>Part A applies to downloads of ePAD source code and/or data from ePAD.</li>
        <li>Part B applies to contributions of software and/or data to ePAD (including making revisions of or additions to code and/or data already in ePAD), which may include source or object code.</li>
        </ol>
        <p>Your download, copying, modifying, displaying, distributing or use of any ePAD software and/or data from ePAD (collectively, the "Software") is subject to Part A. Your contribution of software and/or data to ePAD (including any that occurred prior to the first publication of this Agreement) is a "Contribution" subject to Part B. Both Parts A and B shall be governed by and construed in accordance with the laws of the State of California without regard to principles of conflicts of law. Any legal action involving this Agreement or the Research Program will be adjudicated in the State of California. This Agreement shall supersede and replace any license terms that you may have agreed to previously with respect to ePAD.</p>
        <p><strong>PART A. DOWNLOADING AGREEMENT - LICENSE FROM STANFORD WITH RIGHT TO SUBLICENSE ("SOFTWARE LICENSE").</strong></p>
        <ol>
        <li>As used in this Software License, "you" means the individual downloading and/or using, reproducing, modifying, displaying and/or distributing Software and the institution or entity which employs or is otherwise affiliated with you. Stanford hereby grants you, with right to sublicense, with respect to Stanford&rsquo;s rights in the Software, a royalty-free, non-exclusive license to use, reproduce, make derivative works of, display and distribute the Software, provided that: (a) you adhere to all of the terms and conditions of this Software License; (b) in connection with any copy, distribution of, or sublicense of all or any portion of the Software, the terms and conditions in this Software License shall appear in and shall apply to such copy and such sublicense, including without limitation all source and executable forms and on any user documentation, prefaced with the following words: "All or portions of this licensed product have been obtained under license from The Board of Trustees of the Leland Stanford Junior University. and are subject to the following terms and conditions" AND any user interface to the Software or the &ldquo;About&rdquo; information display in the Software will display the following: &ldquo;Powered by ePAD&nbsp;<u>http://epad.stanford.edu;</u>&rdquo; (c) you preserve and maintain all applicable attributions, copyright notices and licenses included in or applicable to the Software; (d) modified versions of the Software must be clearly identified and marked as such, and must not be misrepresented as being the original Software; and (e) you consider making, but are under no obligation to make, the source code of any of your modifications to the Software freely available to others on an open source basis.</li>
        <li>The license granted in this Software License includes without limitation the right to (i) incorporate the Software into your proprietary programs (subject to any restrictions applicable to such programs), (ii) add your own copyright statement to your modifications of the Software, and (iii) provide additional or different license terms and conditions in your sublicenses of modifications of the Software; provided that in each case your use, reproduction or distribution of such modifications otherwise complies with the conditions stated in this Software License.</li>
        <li>This Software License does not grant any rights with respect to third party software, except those rights that Stanford has been authorized by a third party to grant to you, and accordingly you are solely responsible for (i) obtaining any permissions from third parties that you need to use, reproduce, make derivative works of, display and distribute the Software, and (ii) informing your sublicensees, including without limitation your end-users, of their obligations to secure any such required permissions.</li>
        <li>You agree that you will use the Software in compliance with all applicable laws, policies and regulations including, but not limited to, those applicable to Personal Health Information (&ldquo;PHI&rdquo;) and subject to the Institutional Review Board requirements of your institution, if applicable. The Software has been designed for research purposes only and has not been reviewed or approved by the Food and Drug Administration or by any other agency. YOU ACKNOWLEDGE AND AGREE THAT CLINICAL APPLICATIONS ARE NEITHER RECOMMENDED NOR ADVISED. Any commercialization of the Software is at the sole risk of you and the party or parties engaged in such commercialization. If Software is used in a commercial application, you shall notify Stanford promptly of such use. You further agree to use, reproduce, make derivative works of, display and distribute the Software in compliance with all applicable governmental laws, regulations and orders, including without limitation those relating to export and import control.</li>
        <li>You shall not disable or otherwise alter the Software code functionality that reports aggregate and anonymized ePAD data usage statistics.</li>
        <li>You or your institution, as applicable, will indemnify, hold harmless, and defend Stanford against any third party claim of any kind made against Stanford arising out of or related to the exercise of any rights granted under this Agreement, the provision of Software, or the breach of this Agreement. Stanford provides the Software&nbsp;<strong>AS IS</strong>and&nbsp;<strong>WITH ALL FAULTS</strong>. Stanford makes no representations and extends no warranties of any kind, either express or implied. Among other things, Stanford disclaims any express or implied warranty in the Software:
        <ol>
        <li>of merchantability, of fitness for a particular purpose,</li>
        <li>of non-infringement or</li>
        <li>arising out of any course of dealing.</li>
        </ol>
        </li>
        <li>Title and copyright to the Program and any associated documentation shall at all times remain with Stanford, and Licensee agrees to preserve same. Stanford reserves the right to license the Program at any time for a fee.</li>
        <li>None of the names, logos or trademarks of Stanford or any of Stanford&rsquo;s affiliates or any of the Contributors, or any funding agency, may be used to endorse or promote products produced in whole or in part by operation of the Software or derived from or based on the Software without specific prior written permission from the applicable party.</li>
        <li>Any use, reproduction or distribution of the Software which is not in accordance with this Software License shall automatically revoke all rights granted to you under this Software License and render Paragraphs 1 and 2 of this Software License null and void.</li>
        <li>This Software License does not grant any rights in or to any intellectual property owned by Stanford or any Contributor except those rights expressly granted hereunder.</li>
        </ol>
        <p><strong>PART B. CONTRIBUTION AGREEMENT - LICENSE TO STANFORD WITH RIGHT TO SUBLICENSE ("CONTRIBUTION AGREEMENT").</strong></p>
        <ol>
        <li>As used in this Contribution Agreement, "you" means an individual providing a Contribution to ePAD and the institution or entity which employs or is otherwise affiliated with you.</li>
        <li>This Contribution Agreement applies to all Contributions made to ePAD at any time. By making a Contribution you represent that: (i) you are legally authorized and entitled by ownership or license to make such Contribution and to grant all licenses granted in this Contribution Agreement with respect to such Contribution; (ii) if your Contribution includes any patient data, all such data is de-identified in accordance with U.S. confidentiality and security laws and requirements, including but not limited to the Health Insurance Portability and Accountability Act (HIPAA) and its regulations, and your disclosure of such data for the purposes contemplated by this Agreement is properly authorized and in compliance with all applicable laws and regulations; (iii) you have preserved in the Contribution all applicable attributions, copyright notices and licenses for any third party software or data included in the Contribution; and (iv) you will not disable or otherwise alter the Software code functionality that reports aggregate and anonymized ePAD data usage statistics.</li>
        <li>Except for the licenses you grant in this Agreement, you reserve all right, title and interest in your Contribution.</li>
        <li>You hereby grant to Stanford, with the right to sublicense, a perpetual, worldwide, non-exclusive, no charge, royalty-free, irrevocable license to use, reproduce, make derivative works of, display and distribute the Contribution. If your Contribution is protected by patent, you hereby grant to Stanford, with the right to sublicense, a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable license under your interest in patent rights embodied in the Contribution, to make, have made, use, sell and otherwise transfer your Contribution, alone or in combination with ePAD or otherwise.</li>
        <li>You acknowledge and agree that Stanford may incorporate your Contribution into ePAD and may make your Contribution as incorporated available to members of the public on an open source basis under terms substantially in accordance with the Software License set forth in Part A of this Agreement. You further acknowledge and agree that Stanford shall have no liability arising in connection with claims resulting from your breach of any of the terms of this Agreement.</li>
        <li><strong>YOU WARRANT THAT TO THE BEST OF YOUR KNOWLEDGE YOUR CONTRIBUTION DOES NOT CONTAIN ANY CODE OBTAINED BY YOU UNDER AN OPEN SOURCE LICENSE THAT REQUIRES OR PRESCRIBES DISTRIBUTION OF DERIVATIVE WORKS UNDER SUCH OPEN SOURCE LICENSE.&nbsp;</strong>(By way of non-limiting example, you will not contribute any code obtained by you under the GNU General Public License or other so-called "reciprocal" license.)</li>
        </ol>
        <p>&nbsp;</p>
        <p><strong>BY CLICKING ON &ldquo;ACCEPT,&rdquo; DOWNLOADING, OR OTHERWISE USING EPAD, YOU AGREE TO THE FOLLOWING TERMS AND CONDITIONS:</strong></p>
        <p><strong>Stanford ACADEMIC SOFTWARE LICENSE AGREEMENT FOR</strong></p>
        <p>&ldquo;ePAD Annotation Platform for Radiology Images and Plugins&rdquo;</p>
        <p>version 7/27/2020</p>
        <ol>
        <li>This License Agreement (&ldquo;Agreement&rdquo;) is by and between the party identified below (&ldquo;Licensee&rdquo;) and The Board of Trustees of the Leland Stanford Junior University (&ldquo;Stanford&rdquo;). &ldquo;ePAD Annotation Platform for Radiology Images&rdquo; includes Web Services and core platform for managing images and image annotations. &ldquo;ePAD Plugins&rdquo; include the ePAD Viewer and server-side software modules for processing imaging data, including any accompanying information, materials or manuals (collectively &ldquo;Program&rdquo;), Licensee agrees to be bound by the terms of this Agreement. If you do not agree to the terms of this Agreement, do not accept the terms of this License Agreement; if you have downloaded the Program, immediately delete it from your system.</li>
        <li>Stanford grants to Licensee a royalty-free, nonexclusive, and nontransferable license to use the Program furnished hereunder upon the terms and conditions set out below. Licensee shall have no right in the intellectual property of Stanford not expressly licensed under this Agreement, including but not limited to inventions and patents or patent applications.</li>
        <li>Licensee acknowledges that the Program is a research tool in development that it is provided hereunder as is, without any accompanying services, support, error corrections or improvements from Stanford.</li>
        <li>Licensee warrants that Licensee will not remove or export any part of the Program from the United States except in full compliance with all United States and other applicable laws and regulations.</li>
        <li>Licensee will use the Program in compliance with all applicable laws, policies and regulations including, but not limited to, those applicable to Personal Health Information (&ldquo;PHI&rdquo;) and subject to the Institutional Review Board requirements of the Licensee&rsquo;s institution, if applicable. The Software has been designed for research purposes only and has not been reviewed or approved by the Food and Drug Administration or by any other agency. YOU ACKNOWLEDGE AND AGREE THAT CLINICAL APPLICATIONS ARE NEITHER RECOMMENDED NOR ADVISED. Any commercialization of the Software is at the sole risk of you and the party or parties engaged in such commercialization. If Software is used in a commercial application, you shall notify Stanford promptly of such use.</li>
        <li>You shall not disable or otherwise alter the Software code functionality that reports aggregate and anonymized ePAD data usage statistics.</li>
        <li>Licensee will indemnify, hold harmless, and defend Stanford against any third party claim of any kind made against Stanford arising out of or related to the exercise of any rights granted under this Agreement, the provision of Licensee Derivatives, or the breach of this Agreement by Licensee. Stanford provides the Program AS IS and WITH ALL FAULTS. Stanford makes no representations and extends no warranties of any kind, either express or implied. Among other things, Stanford disclaims any express or implied warranty:
        <ol>
        <li>of merchantability, of fitness for a particular purpose,</li>
        <li>of non-infringement or</li>
        <li>arising out of any course of dealing.</li>
        </ol>
        </li>
        <li>Title and copyright to the Program and any associated documentation shall at all times remain with Stanford, and Licensee agrees to preserve same.</li>
        <li>Stanford reserves the right to terminate this Agreement by email notice at any time upon determination that Licensee has breached the terms. Upon receipt of such notice, Licensee agrees to discontinue use of the Program and delete or destroy all copies.</li>
        <li>This Agreement is governed by the laws of the State of California, without regard to its conflict of laws doctrine. Any legal action involving this Agreement or the Research Program will be adjudicated in the State of California.</li>
        </ol>
    </div>
    <form class="form-actions" action="${url.loginAction}" method="POST">
        <input class="${properties.kcButtonClass!} ${properties.kcButtonPrimaryClass!} ${properties.kcButtonLargeClass!}" name="accept" id="kc-accept" type="submit" value="${msg("doAccept")}"/>
        <input class="${properties.kcButtonClass!} ${properties.kcButtonDefaultClass!} ${properties.kcButtonLargeClass!}" name="cancel" id="kc-decline" type="submit" value="${msg("doDecline")}"/>
    </form>
    <div class="clearfix"></div>
    </#if>
</@layout.registrationLayout>
